/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Assessment = IDL.Record({
  'id' : IDL.Nat,
  'maxScore' : IDL.Nat,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'term' : IDL.Text,
});
export const Mark = IDL.Record({
  'studentId' : IDL.Nat,
  'score' : IDL.Nat,
  'subjectId' : IDL.Nat,
  'assessmentId' : IDL.Nat,
});
export const Student = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'grade' : IDL.Text,
});
export const Subject = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrUpdateMark' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAssessment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createStudent' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'createSubject' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'deleteAssessment' : IDL.Func([IDL.Nat], [], []),
  'deleteMark' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'deleteStudent' : IDL.Func([IDL.Nat], [], []),
  'deleteSubject' : IDL.Func([IDL.Nat], [], []),
  'getAllAssessments' : IDL.Func([], [IDL.Vec(Assessment)], ['query']),
  'getAllMarks' : IDL.Func([], [IDL.Vec(Mark)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMarksByAssessment' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Mark)],
      ['query'],
    ),
  'getMarksByStudent' : IDL.Func([IDL.Nat], [IDL.Vec(Mark)], ['query']),
  'importMarks' : IDL.Func([IDL.Vec(Mark)], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'updateAssessment' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'updateStudent' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateSubject' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Assessment = IDL.Record({
    'id' : IDL.Nat,
    'maxScore' : IDL.Nat,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'term' : IDL.Text,
  });
  const Mark = IDL.Record({
    'studentId' : IDL.Nat,
    'score' : IDL.Nat,
    'subjectId' : IDL.Nat,
    'assessmentId' : IDL.Nat,
  });
  const Student = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'grade' : IDL.Text,
  });
  const Subject = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrUpdateMark' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAssessment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createStudent' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'createSubject' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'deleteAssessment' : IDL.Func([IDL.Nat], [], []),
    'deleteMark' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'deleteStudent' : IDL.Func([IDL.Nat], [], []),
    'deleteSubject' : IDL.Func([IDL.Nat], [], []),
    'getAllAssessments' : IDL.Func([], [IDL.Vec(Assessment)], ['query']),
    'getAllMarks' : IDL.Func([], [IDL.Vec(Mark)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMarksByAssessment' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Mark)],
        ['query'],
      ),
    'getMarksByStudent' : IDL.Func([IDL.Nat], [IDL.Vec(Mark)], ['query']),
    'importMarks' : IDL.Func([IDL.Vec(Mark)], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'updateAssessment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'updateStudent' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateSubject' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };