/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Assessment {
  'id' : bigint,
  'maxScore' : bigint,
  'date' : string,
  'name' : string,
  'term' : string,
}
export interface Mark {
  'studentId' : bigint,
  'score' : bigint,
  'subjectId' : bigint,
  'assessmentId' : bigint,
}
export interface Student { 'id' : bigint, 'name' : string, 'grade' : string }
export interface Subject { 'id' : bigint, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrUpdateMark' : ActorMethod<[bigint, bigint, bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAssessment' : ActorMethod<[string, string, string, bigint], bigint>,
  'createStudent' : ActorMethod<[string, string], bigint>,
  'createSubject' : ActorMethod<[string], bigint>,
  'deleteAssessment' : ActorMethod<[bigint], undefined>,
  'deleteMark' : ActorMethod<[bigint, bigint, bigint], undefined>,
  'deleteStudent' : ActorMethod<[bigint], undefined>,
  'deleteSubject' : ActorMethod<[bigint], undefined>,
  'getAllAssessments' : ActorMethod<[], Array<Assessment>>,
  'getAllMarks' : ActorMethod<[], Array<Mark>>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getAllSubjects' : ActorMethod<[], Array<Subject>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMarksByAssessment' : ActorMethod<[bigint, bigint], Array<Mark>>,
  'getMarksByStudent' : ActorMethod<[bigint], Array<Mark>>,
  'importMarks' : ActorMethod<[Array<Mark>], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'updateAssessment' : ActorMethod<
    [bigint, string, string, string, bigint],
    undefined
  >,
  'updateStudent' : ActorMethod<[bigint, string, string], undefined>,
  'updateSubject' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];